# Generated by Django 2.1.3 on 2018-11-28 18:21

from django.db import migrations, models
import django.utils.timezone
import mytube.apps.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='original_file_name',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(
                upload_to=mytube.apps.video.models.video_upload_to),
        ),
    ]
