# Generated by Django 2.1.3 on 2018-11-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20181128_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted')], default='PUBLIC', max_length=8),
        ),
    ]
