# Generated by Django 2.1.3 on 2018-11-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20181129_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
