# Generated by Django 2.1.3 on 2018-11-29 18:17

from django.db import migrations, models
import mytube.apps.video.models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20181129_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='preview_thumb',
            field=models.FileField(blank=True, null=True, upload_to=mytube.apps.video.models.thumb_upload_to),
        ),
    ]
